from __future__ import annotations

from dataclasses import dataclass, field

import gymnasium as gym
import numpy as np
from etils import epath

# ─────────────────────────── Quaternion helpers ───────────────────────────
# All quaternions are w-first: [w, x, y, z], shape (N, 4)


def _quat_conjugate(q: np.ndarray) -> np.ndarray:
    conj = q.copy()
    conj[:, 1:] *= -1
    return conj


def _quat_mul(q1: np.ndarray, q2: np.ndarray) -> np.ndarray:
    w1, x1, y1, z1 = q1[:, 0], q1[:, 1], q1[:, 2], q1[:, 3]
    w2, x2, y2, z2 = q2[:, 0], q2[:, 1], q2[:, 2], q2[:, 3]
    return np.stack(
        [
            w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
            w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
            w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
            w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2,
        ],
        axis=1,
    )


def _quat_to_axis_angle(q: np.ndarray) -> np.ndarray:
    """Convert unit quaternion (w-first: [w, x, y, z]) to axis-angle vector (N, 3).

    Adapted from PyTorch3D (real-part-last) to MuJoCo w-first convention.
    Uses atan2 + Taylor expansion for numerical stability near zero rotation.
    """
    xyz = q[:, 1:]  # (N, 3) imaginary part
    w = q[:, 0:1]  # (N, 1) real part
    norms = np.linalg.norm(xyz, axis=-1, keepdims=True)  # (N, 1)
    half_angle = np.arctan2(norms, w)  # (N, 1)
    angle = 2.0 * half_angle  # (N, 1)
    small = np.abs(angle) < 1e-6  # (N, 1)
    # sin(x/2)/x:  for small x use Taylor  0.5 - x²/48
    safe_angle = np.where(small, 1.0, angle)
    sin_half_over_angle = np.where(
        small,
        0.5 - angle**2 / 48.0,
        np.sin(half_angle) / safe_angle,
    )
    return xyz / sin_half_over_angle  # (N, 3)


from unilab.base import registry
from unilab.base.backend import create_backend
from unilab.base.np_env import NpEnvState
from unilab.envs.manipulation.inhand_rot_allegro.base import AllegroBaseCfg, AllegroBaseMjEnv

# ─────────────────────────── Configuration ────────────────────────────


@dataclass
class RewardConfig:
    scales: dict[str, float] = field(
        default_factory=lambda: {
            "rotate": 1.25,  # angular velocity along target rotation axis
            "obj_linvel": -0.3,  # penalise object linear motion (keep it stable)
            "pose_diff": -0.3,  # penalise drift from initial grasp pose
            "torque": -0.1,  # penalise large joint effort
            "work": -2.0,  # penalise mechanical work done
        }
    )
    # Rotation reward clipped to [angvel_clip_min, angvel_clip_max] rad/s
    angvel_clip_min: float = -0.5
    angvel_clip_max: float = 0.5

    # Object drops below this world-z → episode terminates.
    reset_z_threshold: float = 0.125  # metres


@dataclass
class DomainRandConfig:
    # Small random perturbation added to each joint at reset (rad).
    joint_noise: float = 0.00
    # Random linear velocity injected into ball at reset (m/s).
    ball_vel_noise: float = 0.00
    # Z-offset added to ball position at reset (m).
    ball_z_offset: float = 0.0


@registry.envcfg("AllegroInhandRotation")
@dataclass
class AllegroRotationCfg(AllegroBaseCfg):
    model_file: str = str(epath.Path(__file__).parent / "xml" / "scene.xml")
    max_episode_seconds: float = 20.0  # same as HORA
    reward_config: RewardConfig = field(default_factory=RewardConfig)
    domain_rand: DomainRandConfig = field(default_factory=DomainRandConfig)

    # World-frame unit vector around which to reward rotation.
    # Default (+z) = counterclockwise when viewed from above.
    rotation_axis: tuple = (0.0, 0.0, 1.0)

    # Path to a grasp cache (.npy) generated by pre_grasp.py.
    # Empty string = auto-detect grasps/grasp_50k.npy beside this file.
    grasp_cache_path: str = ""

    # If True, disable grasp cache loading (for grasp generation mode).
    gen_grasp: bool = False


# ─────────────────────────── Environment ──────────────────────────────


@registry.env("AllegroInhandRotation", sim_backend="mujoco")
class AllegroRotationMj(AllegroBaseMjEnv):
    def __init__(self, cfg: AllegroRotationCfg, num_envs: int = 1, backend_type: str = "mujoco"):
        backend = create_backend(backend_type, cfg.model_file, num_envs, cfg.sim_dt)
        super().__init__(cfg, backend, num_envs)
        self._enable_reward_log = True

        # Normalisation constants for joint-position observation.
        self._dof_range = self._ctrl_upper - self._ctrl_lower  # (16,)
        self._dof_mid = (self._ctrl_upper + self._ctrl_lower) / 2.0  # (16,)

        # Rotation axis as a broadcast-ready (3,) unit vector.
        axis = np.array(cfg.rotation_axis, dtype=self._np_dtype)
        self._rot_axis = axis / np.linalg.norm(axis)

        # Grasp cache loaded lazily on first reset
        self._grasp_cache = None
        self._grasp_cache_loaded = False

        self._init_reward_functions()
        self._init_obs_space()

    # ── Spaces ──────────────────────────────────────────────────────

    def _init_obs_space(self):
        # Last 3 timesteps of [dof_pos_norm(16) + targets(16) + ball_pos(3)] = 3 * 35 = 105
        self._observation_space = gym.spaces.Box(
            low=-np.inf, high=np.inf, shape=(105,), dtype=float
        )

    @property
    def observation_space(self) -> gym.spaces.Box:
        return self._observation_space

    # ── Reward functions ─────────────────────────────────────────────

    def _init_reward_functions(self):
        self._reward_fns = {
            "rotate": self._reward_rotate,
            "obj_linvel": self._reward_obj_linvel,
            "pose_diff": self._reward_pose_diff,
            "torque": lambda s: self._reward_torque(s.info),
            "work": lambda s: self._reward_work(s.info),
        }

    def _reward_rotate(self, state: NpEnvState) -> np.ndarray:
        """Reward the component of ball angular velocity along the target axis.
        Angular velocity is derived from quaternion finite difference, not physics state."""
        ball_angvel = state.info.get(
            "ball_angvel_from_quat",
            np.zeros((self._num_envs, 3), dtype=self._np_dtype),
        )
        vec_dot = ball_angvel @ self._rot_axis  # (N,)
        r = self._cfg.reward_config
        return np.clip(vec_dot, r.angvel_clip_min, r.angvel_clip_max)

    def _reward_obj_linvel(self, state: NpEnvState) -> np.ndarray:
        """L1 penalty on ball linear velocity (encourages pure spin, no translation)."""
        ball_linvel = state.info.get(
            "ball_linvel", np.zeros((self._num_envs, 3), dtype=self._np_dtype)
        )
        return np.sum(np.abs(ball_linvel), axis=1)

    def _reward_pose_diff(self, state: NpEnvState) -> np.ndarray:
        """Penalise hand-joint drift from the initial grasp configuration."""
        diff = self.get_hand_dof_pos() - state.info["init_pose"]  # (N, 16)
        return np.sum(np.square(diff), axis=1)

    def _reward_torque(self, info: dict) -> np.ndarray:
        """Torque penalty: sum of squared torques."""
        torques = info.get(
            "torques", np.zeros((self._num_envs, self._NUM_HAND_DOF), dtype=self._np_dtype)
        )
        return np.sum(np.square(torques), axis=1)

    def _reward_work(self, info: dict) -> np.ndarray:
        """Penalise mechanical work: (torque * velocity)^2."""
        torques = info.get(
            "torques", np.zeros((self._num_envs, self._NUM_HAND_DOF), dtype=self._np_dtype)
        )
        dof_vel = info.get(
            "dof_vel", np.zeros((self._num_envs, self._NUM_HAND_DOF), dtype=self._np_dtype)
        )
        work = np.sum(torques * dof_vel, axis=1)
        return np.square(work)

    # ── Core update pipeline ─────────────────────────────────────────

    def update_state(self, state: NpEnvState) -> NpEnvState:
        # Compute velocities using finite differences
        dof_pos = self.get_hand_dof_pos()
        ball_pos = self.get_ball_pos()
        ball_quat = self.get_ball_quat()  # (N, 4) w-first

        dof_vel = (dof_pos - state.info.get("prev_dof_pos", dof_pos)) / self._cfg.ctrl_dt
        ball_linvel = (ball_pos - state.info.get("prev_ball_pos", ball_pos)) / self._cfg.ctrl_dt

        # Angular velocity from quaternion finite difference:
        #   angdiff = quat_to_axis_angle(q_curr * conjugate(q_prev))
        #   angvel  = angdiff / dt
        prev_ball_quat = state.info.get("prev_ball_quat", ball_quat)
        rel_quat = _quat_mul(ball_quat, _quat_conjugate(prev_ball_quat))
        ball_angvel_from_quat = _quat_to_axis_angle(rel_quat) / self._cfg.ctrl_dt

        # Store current positions/orientations for next step
        state.info["prev_dof_pos"] = dof_pos.copy()
        state.info["prev_ball_pos"] = ball_pos.copy()
        state.info["prev_ball_quat"] = ball_quat.copy()
        state.info["ball_angvel_from_quat"] = ball_angvel_from_quat

        # Compute PD torques: torque = Kp * (target - pos) - Kd * vel
        targets = state.info["prev_ctrl"]
        p_gain = self._cfg.control_config.kp
        d_gain = self._cfg.control_config.kd
        torques = p_gain * (targets - dof_pos) - d_gain * dof_vel
        torques = np.clip(torques, -0.5, 0.5)

        state.info["torques"] = torques
        state.info["dof_vel"] = dof_vel
        state.info["ball_linvel"] = ball_linvel

        # Update observation lag history
        dof_pos_norm = 2.0 * (dof_pos - self._dof_mid) / (self._dof_range + 1e-8)

        # Add observation noise
        noise_cfg = self._cfg.noise_config
        if noise_cfg.level > 0.0:
            dof_pos_norm += (
                np.random.uniform(-1.0, 1.0, dof_pos_norm.shape).astype(self._np_dtype)
                * noise_cfg.level
                * noise_cfg.scale_joint_angle
            )

        current_obs = np.concatenate([dof_pos_norm, targets, ball_pos], axis=1)  # (N, 35)

        obs_lag_history = state.info.get(
            "obs_lag_history", np.zeros((self._num_envs, 3, 35), dtype=self._np_dtype)
        )
        obs_lag_history[:, :-1] = obs_lag_history[:, 1:]
        obs_lag_history[:, -1] = current_obs
        state.info["obs_lag_history"] = obs_lag_history

        terminated = self._update_terminated()
        reward, log = self._compute_rewards(state)
        state.info["log"] = log
        obs = self._get_obs(state.info)
        return state.replace(obs=obs, reward=reward, terminated=terminated)

    def _update_terminated(self) -> np.ndarray:
        ball_z = self.get_ball_pos()[:, 2]  # (N,)
        return ball_z < self._cfg.reward_config.reset_z_threshold

    def _compute_rewards(self, state: NpEnvState) -> tuple:
        total = np.zeros(self._num_envs, dtype=self._np_dtype)
        step_count = state.info.get("steps", np.zeros(self._num_envs, dtype=np.uint32))
        should_log = self._enable_reward_log and (int(step_count[0]) % 4 == 0)
        log = {} if should_log else state.info.get("log", {})

        for name, scale in self._cfg.reward_config.scales.items():
            if scale == 0 or name not in self._reward_fns:
                continue
            rew = self._reward_fns[name](state)
            total += rew * scale
            if should_log:
                log[f"reward/{name}"] = float(np.mean(rew * scale))

        if should_log:
            log["reward/total"] = float(np.mean(total))

        return total * self._cfg.ctrl_dt, log

    def _get_obs(self, info: dict) -> np.ndarray:
        """Extract observation from info. Pure function - does not modify state."""
        obs_lag_history = info.get(
            "obs_lag_history", np.zeros((self._num_envs, 3, 35), dtype=self._np_dtype)
        )
        num_envs = obs_lag_history.shape[0]
        return obs_lag_history.reshape(num_envs, -1)

    # ── Reset ────────────────────────────────────────────────────────

    def reset(self, env_indices: np.ndarray) -> tuple:
        num_reset = len(env_indices)
        dr = self._cfg.domain_rand

        # Lazy load grasp cache on first reset
        if not self._grasp_cache_loaded:
            if self._cfg.gen_grasp:
                self._grasp_cache = None
                print("[AllegroRotationMj] gen_grasp=True — using keyframe reset only")
            else:
                _default = epath.Path(__file__).parent / "grasps" / "grasp_50k.npy"
                cache_path = self._cfg.grasp_cache_path or str(_default)
                if not epath.Path(cache_path).exists():
                    raise FileNotFoundError(f"Grasp cache not found: {cache_path}")
                self._grasp_cache = np.load(cache_path).astype(np.float64)
                print(
                    f"[AllegroRotationMj] Loaded {len(self._grasp_cache):,} grasps from {cache_path}"
                )
            self._grasp_cache_loaded = True

        if self._grasp_cache is not None:
            # Sample num_reset random states from the pre-collected grasp cache.
            idx = np.random.randint(0, len(self._grasp_cache), size=num_reset)
            sampled = self._grasp_cache[idx]  # (num_reset, 23) float64
            hand_qpos = sampled[:, :16]  # (num_reset, 16)
            ball_pos = sampled[:, 16:19]  # (num_reset,  3)
            ball_quat = sampled[:, 19:23]  # (num_reset,  4)
        else:
            # Fallback: keyframe pre-grasp pose + small noise.
            hand_qpos = np.broadcast_to(self.default_angles, (num_reset, self._NUM_HAND_DOF)).copy()
            hand_qpos += np.random.uniform(-dr.joint_noise, dr.joint_noise, hand_qpos.shape).astype(
                np.float64
            )
            hand_qpos = np.clip(
                hand_qpos,
                self._ctrl_lower.astype(np.float64),
                self._ctrl_upper.astype(np.float64),
            )

            ball_init_pos = self._init_qpos[self._NUM_HAND_DOF : self._NUM_HAND_DOF + 3]
            ball_pos = np.broadcast_to(ball_init_pos, (num_reset, 3)).copy()
            ball_pos[:, :2] += np.random.uniform(-0.00, 0.00, (num_reset, 2))
            ball_pos[:, 2] += dr.ball_z_offset
            ball_quat = np.tile([1.0, 0.0, 0.0, 0.0], (num_reset, 1))  # w-first, identity

        # Full qpos / qvel arrays.
        qpos = np.concatenate([hand_qpos, ball_pos, ball_quat], axis=1).astype(np.float64)
        qvel = np.zeros((num_reset, self.nv), dtype=np.float64)
        # Tiny random ball velocity to break symmetry.
        qvel[:, self._NUM_HAND_DOF : self._NUM_HAND_DOF + 3] = np.random.uniform(
            -dr.ball_vel_noise, dr.ball_vel_noise, (num_reset, 3)
        )

        # Set state via backend (sets qpos/qvel and runs mj_forward).
        self._backend.set_state(env_indices, qpos, qvel)

        # PD controller starts at the actual reset hand pose.
        init_ctrl = hand_qpos.astype(self._np_dtype)

        # Initialize lag history with current state
        dof_pos_norm = 2.0 * (init_ctrl - self._dof_mid) / (self._dof_range + 1e-8)
        ball_pos_f32 = ball_pos.astype(self._np_dtype)
        init_obs = np.concatenate(
            [dof_pos_norm, init_ctrl, ball_pos_f32], axis=1
        )  # (num_reset, 35)
        obs_lag_history = np.broadcast_to(
            init_obs[:, None, :], (num_reset, 3, 35)
        ).copy()  # (num_reset, 3, 35)

        info = {
            "current_actions": np.zeros((num_reset, self._num_action), dtype=self._np_dtype),
            "last_actions": np.zeros((num_reset, self._num_action), dtype=self._np_dtype),
            "prev_ctrl": init_ctrl,
            "init_pose": init_ctrl.copy(),
            "prev_dof_pos": init_ctrl.copy(),
            "prev_ball_pos": ball_pos_f32.copy(),
            "prev_ball_quat": ball_quat.astype(self._np_dtype).copy(),
            "obs_lag_history": obs_lag_history,
        }

        obs_batch = self._get_obs(info)
        return obs_batch, obs_batch, info
