from __future__ import annotations

from dataclasses import dataclass, field

import gymnasium as gym
import numpy as np
from etils import epath

from unilab.envs import registry
from unilab.envs.mujoco_env.mj_env import MjNpEnvState
from unilab.envs.manipulation.inhand_rot_allegro.base import AllegroBaseCfg, AllegroBaseMjEnv

# ─────────────────────────── Configuration ────────────────────────────


@dataclass
class RewardConfig:
    scales: dict[str, float] = field(
        default_factory=lambda: {
            "rotate":      1.25,   # angular velocity along target rotation axis
            "obj_linvel": -0.3,    # penalise object linear motion (keep it stable)
            "pose_diff":  -0.3,    # penalise drift from initial grasp pose
            "torque":     -0.1,    # penalise large joint effort
            "work":       -2.0,    # penalise mechanical work done
        }
    )
    # Rotation reward clipped to [angvel_clip_min, angvel_clip_max] rad/s
    angvel_clip_min: float = -0.5
    angvel_clip_max: float =  0.5

    # Object drops below this world-z → episode terminates.
    reset_z_threshold: float = 0.125   # metres


@dataclass
class DomainRandConfig:
    # Small random perturbation added to each joint at reset (rad).
    joint_noise: float = 0.00
    # Random linear velocity injected into ball at reset (m/s).
    ball_vel_noise: float = 0.00
    # Z-offset added to ball position at reset (m).
    ball_z_offset: float = 0.0


@registry.envcfg("AllegroInhandRotation")
@dataclass
class AllegroRotationCfg(AllegroBaseCfg):
    model_file: str = str(epath.Path(__file__).parent / "xml" / "scene.xml")
    max_episode_seconds: float = 20.0 # same as HORA
    reward_config: RewardConfig = field(default_factory=RewardConfig)
    domain_rand: DomainRandConfig = field(default_factory=DomainRandConfig)

    # World-frame unit vector around which to reward rotation.
    # Default (+z) = counterclockwise when viewed from above.
    rotation_axis: tuple = (0.0, 0.0, 1.0)

    # Path to a grasp cache (.npy) generated by pre_grasp.py.
    # Empty string = auto-detect grasps/grasp_50k.npy beside this file.
    grasp_cache_path: str = ""

    # If True, disable grasp cache loading (for grasp generation mode).
    gen_grasp: bool = False


# ─────────────────────────── Environment ──────────────────────────────


@registry.env("AllegroInhandRotation", sim_backend="mujoco")
class AllegroRotationMj(AllegroBaseMjEnv):

    def __init__(self, cfg: AllegroRotationCfg, num_envs: int = 1):
        super().__init__(cfg, num_envs)
        self._enable_reward_log = True

        # Normalisation constants for joint-position observation.
        self._dof_range = (self._ctrl_upper - self._ctrl_lower)        # (16,)
        self._dof_mid   = (self._ctrl_upper + self._ctrl_lower) / 2.0  # (16,)

        # Rotation axis as a broadcast-ready (3,) unit vector.
        axis = np.array(cfg.rotation_axis, dtype=self._np_dtype)
        self._rot_axis = axis / np.linalg.norm(axis)

        # Grasp cache loaded lazily on first reset
        self._grasp_cache = None
        self._grasp_cache_loaded = False

        self._init_reward_functions()
        self._init_obs_space()

    # ── Spaces ──────────────────────────────────────────────────────

    def _init_obs_space(self):
        # Last 3 timesteps of [dof_pos_norm(16) + targets(16) + ball_pos(3)] = 3 * 35 = 105
        self._observation_space = gym.spaces.Box(
            low=-np.inf, high=np.inf, shape=(105,), dtype=float
        )

    @property
    def observation_space(self) -> gym.spaces.Box:
        return self._observation_space

    # ── Reward functions ─────────────────────────────────────────────

    def _init_reward_functions(self):
        self._reward_fns = {
            "rotate":      self._reward_rotate,
            "obj_linvel":  self._reward_obj_linvel,
            "pose_diff":   self._reward_pose_diff,
            "torque":      lambda s: self._reward_torque(s.info),
            "work":        lambda s: self._reward_work(s.info),
        }

    def _reward_rotate(self, state: MjNpEnvState) -> np.ndarray:
        """Reward the component of ball angular velocity along the target axis."""
        ball_angvel = self.get_ball_angvel(state)          # (N, 3)
        vec_dot = ball_angvel @ self._rot_axis             # (N,)
        r = self._cfg.reward_config
        return np.clip(vec_dot, r.angvel_clip_min, r.angvel_clip_max)

    def _reward_obj_linvel(self, state: MjNpEnvState) -> np.ndarray:
        """L1 penalty on ball linear velocity (encourages pure spin, no translation)."""
        ball_linvel = state.info.get("ball_linvel", np.zeros((self._num_envs, 3), dtype=self._np_dtype))
        return np.sum(np.abs(ball_linvel), axis=1)

    def _reward_pose_diff(self, state: MjNpEnvState) -> np.ndarray:
        """Penalise hand-joint drift from the initial grasp configuration."""
        diff = self.get_hand_dof_pos(state) - state.info["init_pose"]  # (N, 16)
        return np.sum(np.square(diff), axis=1)

    def _reward_torque(self, info: dict) -> np.ndarray:
        """Torque penalty: sum of squared torques."""
        torques = info.get("torques", np.zeros((self._num_envs, self._NUM_HAND_DOF), dtype=self._np_dtype))
        return np.sum(np.square(torques), axis=1)

    def _reward_work(self, info: dict) -> np.ndarray:
        """Penalise mechanical work: (torque * velocity)^2."""
        torques = info.get("torques", np.zeros((self._num_envs, self._NUM_HAND_DOF), dtype=self._np_dtype))
        dof_vel = info.get("dof_vel", np.zeros((self._num_envs, self._NUM_HAND_DOF), dtype=self._np_dtype))
        work = np.sum(torques * dof_vel, axis=1)
        return np.square(work)

    # ── Core update pipeline ─────────────────────────────────────────

    def update_state(self, state: MjNpEnvState, obs_required: bool = True) -> MjNpEnvState:
        # Compute velocities using finite differences
        dof_pos = self.get_hand_dof_pos(state)
        ball_pos = self.get_ball_pos(state)

        dof_vel = (dof_pos - state.info.get("prev_dof_pos", dof_pos)) / self._cfg.ctrl_dt
        ball_linvel = (ball_pos - state.info.get("prev_ball_pos", ball_pos)) / self._cfg.ctrl_dt

        # Store current positions for next step
        state.info["prev_dof_pos"] = dof_pos.copy()
        state.info["prev_ball_pos"] = ball_pos.copy()

        # Compute PD torques: torque = Kp * (target - pos) - Kd * vel
        targets = state.info["prev_ctrl"]
        p_gain = self._cfg.control_config.kp
        d_gain = self._cfg.control_config.kd
        torques = p_gain * (targets - dof_pos) - d_gain * dof_vel
        torques = np.clip(torques, -0.5, 0.5)

        state.info["torques"] = torques
        state.info["dof_vel"] = dof_vel
        state.info["ball_linvel"] = ball_linvel

        # Update observation lag history
        dof_pos_norm = 2.0 * (dof_pos - self._dof_mid) / (self._dof_range + 1e-8)
        current_obs = np.concatenate([dof_pos_norm, targets, ball_pos], axis=1)  # (N, 35)

        obs_lag_history = state.info.get("obs_lag_history", np.zeros((self._num_envs, 3, 35), dtype=self._np_dtype))
        obs_lag_history[:, :-1] = obs_lag_history[:, 1:]
        obs_lag_history[:, -1] = current_obs
        state.info["obs_lag_history"] = obs_lag_history

        state = self._update_terminated(state)
        state = self._compute_rewards(state)
        if obs_required:
            state.obs = self._get_obs(state, state.info)
        return state

    def _update_terminated(self, state: MjNpEnvState) -> MjNpEnvState:
        ball_z = self.get_ball_pos(state)[:, 2]   # (N,)
        state.terminated = ball_z < self._cfg.reward_config.reset_z_threshold
        return state

    def _compute_rewards(self, state: MjNpEnvState) -> MjNpEnvState:
        total = np.zeros(self._num_envs, dtype=self._np_dtype)
        step_count = state.info.get("steps", np.zeros(self._num_envs, dtype=np.uint32))
        should_log = self._enable_reward_log and (int(step_count[0]) % 4 == 0)
        log = {} if should_log else state.info.get("log", {})

        for name, scale in self._cfg.reward_config.scales.items():
            if scale == 0 or name not in self._reward_fns:
                continue
            rew = self._reward_fns[name](state)
            total += rew * scale
            if should_log:
                log[f"reward/{name}"] = float(np.mean(rew * scale))

        if should_log:
            log["reward/total"] = float(np.mean(total))

        state.info["log"] = log
        state.reward = total * self._cfg.ctrl_dt
        return state

    def _get_obs(self, state: MjNpEnvState, info: dict) -> np.ndarray:
        """Extract observation from state. Pure function - does not modify state."""
        obs_lag_history = info.get("obs_lag_history", np.zeros((self._num_envs, 3, 35), dtype=self._np_dtype))
        num_envs = obs_lag_history.shape[0]
        return obs_lag_history.reshape(num_envs, -1)

    # ── Reset ────────────────────────────────────────────────────────

    def reset(self, env_indices: np.ndarray) -> tuple[np.ndarray, np.ndarray, dict]:
        num_reset = len(env_indices)
        dr = self._cfg.domain_rand

        # Lazy load grasp cache on first reset
        if not self._grasp_cache_loaded:
            if self._cfg.gen_grasp:
                self._grasp_cache = None
                print("[AllegroRotationMj] gen_grasp=True — using keyframe reset only")
            else:
                _default = epath.Path(__file__).parent / "grasps" / "grasp_50k.npy"
                cache_path = self._cfg.grasp_cache_path or str(_default)
                if not epath.Path(cache_path).exists():
                    raise FileNotFoundError(f"Grasp cache not found: {cache_path}")
                self._grasp_cache = np.load(cache_path).astype(np.float64)
                print(f"[AllegroRotationMj] Loaded {len(self._grasp_cache):,} grasps from {cache_path}")
            self._grasp_cache_loaded = True

        if self._grasp_cache is not None:
            # Sample num_reset random states from the pre-collected grasp cache.
            idx = np.random.randint(0, len(self._grasp_cache), size=num_reset)
            sampled   = self._grasp_cache[idx]   # (num_reset, 23) float64
            hand_qpos = sampled[:, :16]           # (num_reset, 16)
            ball_pos  = sampled[:, 16:19]         # (num_reset,  3)
            ball_quat = sampled[:, 19:23]         # (num_reset,  4)
        else:
            # Fallback: keyframe pre-grasp pose + small noise.
            hand_qpos = np.broadcast_to(self.default_angles, (num_reset, self._NUM_HAND_DOF)).copy()
            hand_qpos += np.random.uniform(
                -dr.joint_noise, dr.joint_noise, hand_qpos.shape
            ).astype(np.float64)
            hand_qpos = np.clip(
                hand_qpos,
                self._ctrl_lower.astype(np.float64),
                self._ctrl_upper.astype(np.float64),
            )

            ball_init_pos = self._init_qpos[self._NUM_HAND_DOF : self._NUM_HAND_DOF + 3]
            ball_pos = np.broadcast_to(ball_init_pos, (num_reset, 3)).copy()
            ball_pos[:, :2] += np.random.uniform(-0.00, 0.00, (num_reset, 2))
            ball_pos[:, 2] += dr.ball_z_offset
            ball_quat = np.tile([1.0, 0.0, 0.0, 0.0], (num_reset, 1))  # w-first, identity

        # Full qpos / qvel arrays.
        qpos = np.concatenate([hand_qpos, ball_pos, ball_quat], axis=1).astype(np.float64)
        qvel = np.zeros((num_reset, self.nv), dtype=np.float64)
        # Tiny random ball velocity to break symmetry.
        qvel[:, self._NUM_HAND_DOF : self._NUM_HAND_DOF + 3] = np.random.uniform(
            -dr.ball_vel_noise, dr.ball_vel_noise, (num_reset, 3)
        )

        # Build physics state vectors and compute sensors.
        ps = np.zeros((num_reset, self.physics_state_dim), dtype=np.float64)
        ps[:, self._idx_qpos : self._idx_qpos + self.nq] = qpos
        ps[:, self._idx_qvel : self._idx_qvel + self.nv] = qvel
        sensor_data = self._compute_sensor_batch_from_state(ps)
        ps_f32 = ps.astype(self._np_dtype)

        # PD controller starts at the actual reset hand pose.
        init_ctrl = hand_qpos.astype(self._np_dtype)

        # Initialize lag history with current state
        dof_pos_norm = 2.0 * (init_ctrl - self._dof_mid) / (self._dof_range + 1e-8)
        ball_pos_f32 = ball_pos.astype(self._np_dtype)
        init_obs = np.concatenate([dof_pos_norm, init_ctrl, ball_pos_f32], axis=1)  # (num_reset, 35)
        obs_lag_history = np.broadcast_to(init_obs[:, None, :], (num_reset, 3, 35)).copy()  # (num_reset, 3, 35)

        info = {
            "current_actions": np.zeros((num_reset, self._num_action), dtype=self._np_dtype),
            "last_actions":    np.zeros((num_reset, self._num_action), dtype=self._np_dtype),
            "prev_ctrl":       init_ctrl,
            "init_pose":       init_ctrl.copy(),
            "prev_dof_pos":    init_ctrl.copy(),
            "prev_ball_pos":   ball_pos_f32.copy(),
            "obs_lag_history": obs_lag_history,
        }

        obs_state = MjNpEnvState(
            physics_state=ps_f32, sensor_data=sensor_data,
            obs=None, reward=None, terminated=None, truncated=None, ctrl=None,
            info=info,
        )
        obs_batch = self._get_obs(obs_state, info)
        return ps_f32, obs_batch, info
