name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "LICENSE"
      - ".github/CODEOWNERS"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  UV_FROZEN: "1"

jobs:
  ruff-lint:
    timeout-minutes: 5
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Install dependencies(only dev group)
        run: uv sync --only-group dev
      - name: Check
        run: uv run --no-sync ruff check --output-format=github .

  ruff-format:
    timeout-minutes: 5
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Install dependencies(only dev group)
        run: uv sync --only-group dev
      - name: Check
        run: uv run --no-sync ruff format --check .

  mypy:
    timeout-minutes: 10
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Install dependencies
        run: uv sync
      - name: Check
        run: uv run mypy src/unilab

  pyright:
    timeout-minutes: 10
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Install dependencies
        run: uv sync
      - name: Check
        run: uv run pyright

  test:
    strategy:
      matrix:
        os: [ubuntu-slim]
    #     python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          # python-version: ${{ matrix.python-version }}
          python-version: '3.11'
      - name: Install dependencies
        run: uv sync --extra motrix
      - name: Test with coverage
        run: uv run pytest -m "not slow and not veryslow" --cov=unilab --cov-report markdown-append:$GITHUB_STEP_SUMMARY --cov-fail-under=10
